import type { Metadata } from "next";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuSub,
  NavigationMenuTrigger,
} from "@radix-ui/react-navigation-menu";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="p-6  items-center justify-between bg-[#0f1f47] flex relative">
          <img src="/a.webp" alt="Logo" className="w-22 h-22 select-none" draggable="false" />
          <NavigationMenu>
            <NavigationMenuList className="flex flex-row gap-2">
              <NavigationMenuItem>
                <NavigationMenuTrigger className="text-xl text-[#b3bdb3] flex cursor-pointer p-2 items-center gap-1 hover:bg-blue-400 hover:text-white">
                  ADMISSIONS
                  <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className="inline-block ml-1">
                    <path d="M5 8L10 13L15 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </NavigationMenuTrigger>

                <NavigationMenuContent className="absolute top-full bg-white text-blue-400  shadow-md w-2xs">
                  <ul className="flex flex-col gap-2">
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Undergraduate</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Graduate</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Lifelong Learning</Link>
                      </NavigationMenuLink>
                    </li>
                  </ul>
                </NavigationMenuContent>
              </NavigationMenuItem>


              <NavigationMenuItem>
                <NavigationMenuTrigger className=" text-xl text-[#b3bdb3] flex p-2 cursor-pointer items-center gap-1 hover:bg-blue-400 hover:text-white">
                  RESEARCH
                  <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className="inline-block ml-1">
                    <path d="M5 8L10 13L15 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </NavigationMenuTrigger>
                <NavigationMenuContent className="absolute top-full bg-white text-blue-400 shadow-md w-2xs">
                  <ul className="flex flex-col gap-2">
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Engage with us</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Support for researchers</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Using research to engage</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Recognition</Link>
                      </NavigationMenuLink>
                    </li>
                  </ul>
                </NavigationMenuContent>
              </NavigationMenuItem>

              <NavigationMenuItem>
                <NavigationMenuTrigger className=" text-xl text-[#b3bdb3] flex cursor-pointer p-2 items-center gap-1 hover:bg-blue-400 hover:text-white">
                  NEWS & EVENTS
                  <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className="inline-block ml-1">
                    <path d="M5 8L10 13L15 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </NavigationMenuTrigger>
                <NavigationMenuContent className="absolute top-full bg-white text-blue-400 shadow-md w-2xs">
                  <ul className="flex flex-col gap-2">
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Events</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Pulse</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Features</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Oxford profiles</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Filming in Oxford</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Find an Expert</Link>
                      </NavigationMenuLink>
                    </li>
                  </ul>
                </NavigationMenuContent>
              </NavigationMenuItem>

              <NavigationMenuItem>
                <NavigationMenuTrigger className=" text-xl text-[#b3bdb3] flex cursor-pointer p-2 items-center gap-1 hover:bg-blue-400 hover:text-white">
                  ABOUT
                  <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className="inline-block ml-1">
                    <path d="M5 8L10 13L15 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </NavigationMenuTrigger>
                <NavigationMenuContent className="absolute top-full bg-white text-blue-400 shadow-md w-2xs">
                  <ul className="flex flex-col gap-2">
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Events</Link>
                      </NavigationMenuLink>
                    </li>
                    <li className="hover:bg-blue-400 hover:text-white p-2 cursor-pointer">
                      <NavigationMenuLink asChild>
                        <Link href="/">Pulse</Link>
                      </NavigationMenuLink>
                    </li>
                  </ul>
                </NavigationMenuContent>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
          <div className="relative flex items-center">
            <div className="p-2 bg-[#081c34] text-[#b3bdb3] flex items-center justify-center h-10 min-w-[80px] gap-1 cursor-pointer hover:bg-[#00142b] hover:text-white">
              <span className="text-sm leading-none">Colleges</span>
              <svg width="14" height="14" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className="ml-1 text-[#b3bdb3]">
                <path d="M5 8L10 13L15 8Z" />
              </svg>
            </div>
            <div className="p-2 bg-[#081c34] text-[#b3bdb3] flex items-center justify-center h-10 min-w-[80px] gap-1 cursor-pointer hover:text-white">
              <span className="text-sm leading-none">Divisions & departments</span>
              <svg width="14" height="14" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className="ml-1 text-[#b3bdb3]">
                <path d="M5 8L10 13L15 8Z" />
              </svg>
            </div>
            <input
              type="text"
              className="p-2 pr-10 text-white bg-[#203c5c] placeholder-white focus:bg-white focus:text-black focus:placeholder-gray-400 transition-colors duration-200 outline-none"
              placeholder="Search..."
              id="navbar-search-input"
            />
            <button
              type="button"
              tabIndex={-1}
              className="absolute right-2 top-1/2 -translate-y-1/2 p-1 rounded focus:outline-none transition-colors duration-200 bg-transparent cursor-pointer"
              style={{ pointerEvents: 'auto' }}
              aria-label="Search"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                className="transition-colors duration-200"
                id="navbar-search-icon"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 21l-4.35-4.35m0 0A7.5 7.5 0 104.5 4.5a7.5 7.5 0 0012.15 12.15z"
                  className="search-icon-path"
                />
              </svg>
            </button>
            <style>{`
              #navbar-search-input:focus ~ button #navbar-search-icon .search-icon-path {
                stroke: #888;
              }
              #navbar-search-icon .search-icon-path {
                stroke: #fff;
                transition: stroke 0.2s;
              }
              #navbar-search-input:focus {
                background: #fff !important;
                color: #000 !important;
              }
            `}</style>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
